### ISSUE TITLE
ESP exception during intellisense

### ISSUE THREAD

**Issue by llde** [shadeMe/Construction-Set-Extender#8]
Hi, I found that I plugin I was working on yesterday is causing now an exception in the last Dev version (Once in a whiles),  while it hard crash with the release

This is the console trace:
`[SE]	IntelliSense Backend update task failed! Exception: System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Collections.Generic.Dictionary`2.Initialize(Int32 capacity)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Gma.DataStructures.StringSearch.PatriciaTrieNode`1.GetOrCreateChild(StringPartition key, TValue value)
   at Gma.DataStructures.StringSearch.PatriciaTrieNode`1.Add(StringPartition keyRest, TValue value)
   at Gma.DataStructures.StringSearch.PatriciaTrieNode`1.GetOrCreateChild(StringPartition key, TValue value)
   at Gma.DataStructures.StringSearch.PatriciaTrieNode`1.Add(StringPartition keyRest, TValue value)
   at Gma.DataStructures.StringSearch.PatriciaTrieNode`1.GetOrCreateChild(StringPartition key, TValue value)
   at Gma.DataStructures.StringSearch.PatriciaTrieNode`1.Add(StringPartition keyRest, TValue value)
   at Gma.DataStructures.StringSearch.PatriciaTrieNode`1.GetOrCreateChild(StringPartition key, TValue value)
   at Gma.DataStructures.StringSearch.PatriciaTrieNode`1.Add(StringPartition keyRest, TValue value)
   at Gma.DataStructures.StringSearch.PatriciaTrieNode`1.GetOrCreateChild(StringPartition key, TValue value)
   at Gma.DataStructures.StringSearch.PatriciaTrieNode`1.Add(StringPartition keyRest, TValue value)
   at Gma.DataStructures.StringSearch.PatriciaTrieNode`1.GetOrCreateChild(StringPartition key, TValue value)
   at Gma.DataStructures.StringSearch.PatriciaTrie`1.Add(StringPartition keyRest, TValue value)
   at Gma.DataStructures.StringSearch.PatriciaTrie`1.Add(String key, TValue value)
   at cse.scriptEditor.utilities.CaselessFuzzyTrie`1.Add(String Key, TValue Value) in C:\Users\shadeMe\Documents\[TES]\[Code]\[OBSE]\Construction Set Extender\[Components]\ScriptEditor\Utilities.cpp:line 698
   at cse.scriptEditor.intellisense.IntelliSenseItemCollection.Add(String Identifier, IntelliSenseItem Item) in C:\Users\shadeMe\Documents\[TES]\[Code]\[OBSE]\Construction Set Extender\[Components]\ScriptEditor\IntelliSenseBackend.cpp:line 89
   at cse.scriptEditor.intellisense.IntelliSenseBackend.PerformBackgroundUpdateTask(Object Input) in C:\Users\shadeMe\Documents\[TES]\[Code]\[OBSE]\Construction Set Extender\[Components]\ScriptEditor\IntelliSenseBackend.cpp:line 243
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Collections.Generic.Dictionary`2.Initialize(Int32 capacity)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Gma.DataStructures.StringSearch.PatriciaTrieNode`1.GetOrCreateChild(StringPartition key, TValue value)
   at Gma.DataStructures.StringSearch.PatriciaTrieNode`1.Add(StringPartition keyRest, TValue value)
   at Gma.DataStructures.StringSearch.PatriciaTrieNode`1.GetOrCreateChild(StringPartition key, TValue value)
   at Gma.DataStructures.StringSearch.PatriciaTrieNode`1.Add(StringPartition keyRest, TValue value)
   at Gma.DataStructures.StringSearch.PatriciaTrieNode`1.GetOrCreateChild(StringPartition key, TValue value)
   at Gma.DataStructures.StringSearch.PatriciaTrieNode`1.Add(StringPartition keyRest, TValue value)
   at Gma.DataStructures.StringSearch.PatriciaTrieNode`1.GetOrCreateChild(StringPartition key, TValue value)
   at Gma.DataStructures.StringSearch.PatriciaTrieNode`1.Add(StringPartition keyRest, TValue value)
   at Gma.DataStructures.StringSearch.PatriciaTrieNode`1.GetOrCreateChild(StringPartition key, TValue value)
   at Gma.DataStructures.StringSearch.PatriciaTrieNode`1.Add(StringPartition keyRest, TValue value)
   at Gma.DataStructures.StringSearch.PatriciaTrieNode`1.GetOrCreateChild(StringPartition key, TValue value)
   at Gma.DataStructures.StringSearch.PatriciaTrie`1.Add(StringPartition keyRest, TValue value)
   at Gma.DataSt
`
[lollodebug.zip](https://github.com/shadeMe/Construction-Set-Extender/files/10609740/lollodebug.zip)

Attaching the ESP. It contain just a quest and a script,  in the script there is a commented code (it was for a test of an IR bug)

**Comment by shadeMe** [comment]
Hmm, I can't reproduce this on my end; neither with the `forEach` loop inside nor outside the `gameMode` block. Can you upload the crash dump generated by the release version?

**Comment by llde** [comment]
strange, it didn't generate any dump

**Comment by shadeMe** [comment]
Is it otherwise consistently reproducible?

**Comment by llde** [comment]
I cannot reproduce after I removed the comment.
